# Neur-inver  config for  BBP3 training, serialized stims  (each stim is an independent sample)
#
# choose data path depending on facility

data_path:
  #corigpu:     /global/cfs/cdirs/m2043/balewski/neuronBBP3-10kHz_3pr_6stim/dec26_mlPack1  # ontra5
  perlmutter: /global/cfs/cdirs/m2043/balewski/neuronBBP3-10kHz_3pr_6stim/dec26_mlPack1  # ontra5
  #perlmutter: /pscratch/sd/b/balewski/tmp_bbp3_dec26/  # tmp storage for BBP3 prod
  summit: /gpfs/alpine/nro106/proj-shared/neuronBBP-pxxx / # ontra3

data_conf:
    serialize_stims :  True  # False= append  timeBins
    #max_glob_samples_per_epoch: 40000  # optional, reduces epoch size
    num_data_workers: 4  

max_epochs: 12  
batch_size: 512

const_local_batch: True   # True is faster  but LR changes w/ num GPUs
validation_period: [1, 1] # [ period, len] (epochs)
#>>> validation is computed if  epoch%period<len

log_freq_per_epoch: 3
tb_show_graph: True

save_checkpoint: False  # only when loss improves
resume_checkpoint: False  # False: always start over 
# warning: for multi-gpu & resume --> val_loss explodes - no loop over GPUs
  
# APEX: Nvidia streamlined data-parallel  training
# AMP: Automatic Mixed Precision package
# autotune: # activates cudnn.benchmark

opt_pytorch:  
    amp: False
    apex:  False
    autotune:  False
    zerograd: False

train_conf:
    warmup_epochs: 10
    optimizer: [adam, 0.001] # initLR  
    LRsched: { plateau_patience: 8, reduceFactor: 0.11  }

model:
    myId:  6-stims 2023-01
    comment: not optimized ML model

    conv_block: # CNN params
        filter: [30, 60, 90, 120, 180, 240]
        kernel: [ 4, 4, 4, 4,  4,  4]
        pool:   [ 2, 2, 2, 2, 2, 2, ]

    instance_norm_slot: 9
    layer_norm: True
    batch_norm: True

    fc_block: # FC params w/o last layer
        dims: [ 700, 700, 700, 600, 500, 400, 300, 200, 100, 100 ]
        dropFrac: 0.01
