"""Self-contained L5PC cell builder using an *existing* jaxley morphology.

Unlike `l5ttpc.py` — which depends on a NEURON-converted SWC
(`/pscratch/.../Neuron_Jaxley/results_detailed_morphology/L5_TTPC1.swc`,
generated by running NEURON on the BBP `L5_TTPC1_cADpyr232_1` hoc template) and
on hand-ported channels in `Neuron_Jaxley/bbp_channels_jaxley.py` — this builder
needs **no NEURON, no BBP hoc template, and no external repo**:

  * morphology: `morphologies/morph_l5pc_with_axon.swc`, vendored in-repo from
    jaxley's own `tests/swc_files/` (the morphology used in jaxley's official
    "Fitting an L5PC with gradient descent" tutorial).
  * channels: the jaxley-maintained `jaxley_mech.channels.l5pc` library
    (Hay-2011 L5PC channels) + `jaxley.channels.Leak`.

The 19 trainable parameters keep the BBP `parName` ordering (identical to
`l5ttpc.py` and `predictExp.py`'s `param_names`) so this cell is drop-in for the
bridge and param plumbing.  The channel *kinetics* come from `jaxley_mech`
(Hay 2011) and are NOT guaranteed bit-identical to `bbp_channels_jaxley`, and
the morphology is a *different* L5PC than BBP `L5_TTPC1` — so `L5PC_jaxley` is a
faster, fully self-contained L5PC option, not a free drop-in for the CNN already
trained against BBP `L5_TTPC1`.  See docs/phase1/L5PC_existing_morphology.md.
"""

from pathlib import Path
from . import CellSpec, register

# Vendored, in-repo morphology — no /pscratch Neuron_Jaxley dependency.
_MORPH_DIR = Path(__file__).resolve().parent / "morphologies"
_SWC_PATH  = _MORPH_DIR / "morph_l5pc_with_axon.swc"
_STIM_DIR  = Path("/pscratch/sd/k/ktub1999/main/DL4neurons2/stims")

_DT_STIM = 0.1
_DT      = 0.1
_T_MAX   = 500.0
_V_INIT  = -75.0
_NCOMP   = 4   # match l5ttpc.py so morphology cost is the only difference benchmarked

# Reversal potentials / passive defaults (BBP biophysics.hoc convention).
_ENA   =  50.0
_EK    = -85.0
_EH    = -45.0
_GLEAK =  3e-5
_ELEAK = -75.0
_GH_BASE = 8e-5    # uniform apical/basal Ih default (see note in _build)

# Parameter ordering matches `sum_train.yaml['input_meta']['parName']` for a BBP
# cADpyr excitatory cell — same 19 entries as l5ttpc.py, remapped to the
# jaxley_mech channel param keys.  Each entry: (bbp_name, group, jaxley_key).
# "all" = cell-level set.  "capacitance" is a jaxley cell property, not a channel.
_CSV_PARAM_MAP = [
    ("gNaTs2_tbar_NaTs2_t_apical",    "apical", "NaTs2T_gNaTs2T"),
    ("gSKv3_1bar_SKv3_1_apical",      "apical", "SKv3_1_gSKv3_1"),
    ("gImbar_Im_apical",              "apical", "M_gM"),
    ("gIhbar_Ih_dend",                "basal",  "H_gH"),            # also apical
    ("gNaTa_tbar_NaTa_t_axonal",      "axon",   "NaTaT_gNaTaT"),
    ("gK_Tstbar_K_Tst_axonal",        "axon",   "KTst_gKTst"),
    ("gNap_Et2bar_Nap_Et2_axonal",    "axon",   "NapEt2_gNapEt2"),
    ("gSK_E2bar_SK_E2_axonal",        "axon",   "SKE2_gSKE2"),
    ("gCa_HVAbar_Ca_HVA_axonal",      "axon",   "CaHVA_gCaHVA"),
    ("gK_Pstbar_K_Pst_axonal",        "axon",   "KPst_gKPst"),
    ("gCa_LVAstbar_Ca_LVAst_axonal",  "axon",   "CaLVA_gCaLVA"),
    ("g_pas_axonal",                  "axon",   "Leak_gLeak"),
    ("cm_axonal",                     "axon",   "capacitance"),
    ("gSKv3_1bar_SKv3_1_somatic",     "soma",   "SKv3_1_gSKv3_1"),
    ("gNaTs2_tbar_NaTs2_t_somatic",   "soma",   "NaTs2T_gNaTs2T"),
    ("gCa_LVAstbar_Ca_LVAst_somatic", "soma",   "CaLVA_gCaLVA"),
    ("g_pas_somatic",                 "soma",   "Leak_gLeak"),
    ("cm_somatic",                    "soma",   "capacitance"),
    ("e_pas_all",                     "all",    "Leak_eLeak"),
]

PARAM_KEYS    = [entry[0] for entry in _CSV_PARAM_MAP]


def _build():
    """Build the jaxley L5PC cell from the existing morphology + jaxley_mech channels."""
    import jaxley as jx
    from jaxley.channels import Leak
    from jaxley_mech.channels.l5pc import (
        NaTs2T, NaTaT, NapEt2, SKv3_1, KTst, KPst, M, H,
        CaHVA, CaLVA, SKE2, CaPump, CaNernstReversal,
    )

    if not _SWC_PATH.exists():
        raise FileNotFoundError(
            f"vendored L5PC morphology missing: {_SWC_PATH}. Re-download from "
            f"https://raw.githubusercontent.com/jaxleyverse/jaxley/main/"
            f"tests/swc_files/morph_l5pc_with_axon.swc"
        )

    cell = jx.read_swc(str(_SWC_PATH), ncomp=_NCOMP, assign_groups=True)

    cell.set("axial_resistivity", 100.0)
    cell.set("capacitance", 1.0)
    cell.set("v", _V_INIT)
    try:
        cell.apical.set("capacitance", 2.0)
        cell.basal.set("capacitance", 2.0)
    except Exception:
        pass

    # Channel-to-group assignment follows jaxley's official L5PC example.
    cell.insert(Leak())

    cell.soma.insert(NaTs2T()); cell.soma.insert(SKv3_1()); cell.soma.insert(SKE2())
    cell.soma.insert(CaHVA()); cell.soma.insert(CaLVA())
    cell.soma.insert(CaPump()); cell.soma.insert(CaNernstReversal())

    cell.axon.insert(NaTaT()); cell.axon.insert(NapEt2()); cell.axon.insert(SKv3_1())
    cell.axon.insert(KTst()); cell.axon.insert(KPst()); cell.axon.insert(SKE2())
    cell.axon.insert(CaHVA()); cell.axon.insert(CaLVA())
    cell.axon.insert(CaPump()); cell.axon.insert(CaNernstReversal())

    cell.basal.insert(H())

    cell.apical.insert(NaTs2T()); cell.apical.insert(SKv3_1())
    cell.apical.insert(M()); cell.apical.insert(H())

    # Reversal potentials + passive defaults (BBP biophysics.hoc convention).
    cell.set("Leak_gLeak", _GLEAK)
    cell.set("Leak_eLeak", _ELEAK)
    for grp in (cell.soma, cell.axon, cell.apical):
        grp.set("eNa", _ENA); grp.set("eK", _EK)
    for grp in (cell.basal, cell.apical):
        grp.set("eH", _EH)
    # CaPump dynamics — BBP soma/axon decay+gamma.
    cell.soma.set("CaPump_gamma", 0.000609); cell.soma.set("CaPump_decay", 210.485284)
    cell.axon.set("CaPump_gamma", 0.002910); cell.axon.set("CaPump_decay", 287.198731)

    # NOTE: BBP applies a distance-dependent gradient to apical/basal Ih.  This
    # self-contained builder uses a uniform default to avoid a Neuron_Jaxley
    # dependency (jaxley's own L5PC example likewise uses uniform conductances).
    # A distance gradient can be added later via jaxley compartment centers.
    cell.basal.set("H_gH", _GH_BASE)
    cell.apical.set("H_gH", _GH_BASE)

    cell.init_states(delta_t=_DT)
    cell.soma.comp(0).record()

    # Mark each of the 19 CNN-facing params trainable.  gIhbar_Ih_dend applies to
    # both basal and apical (both entries point back to CNN index 3).
    groups = {"soma": cell.soma, "axon": cell.axon, "basal": cell.basal, "apical": cell.apical}
    entry_to_cnn_idx = []
    for cnn_idx, (name, group_key, jax_key) in enumerate(_CSV_PARAM_MAP):
        if name == "gIhbar_Ih_dend":
            groups["basal"].make_trainable(jax_key);   entry_to_cnn_idx.append(cnn_idx)
            groups["apical"].make_trainable(jax_key);  entry_to_cnn_idx.append(cnn_idx)
        elif group_key == "all":
            cell.make_trainable(jax_key);              entry_to_cnn_idx.append(cnn_idx)
        else:
            groups[group_key].make_trainable(jax_key); entry_to_cnn_idx.append(cnn_idx)

    return cell, entry_to_cnn_idx


def _attach_stim(cell, stim_jnp):
    return cell.soma.comp(0).data_stimulate(stim_jnp)


def _attach_record(cell):
    cell.soma.comp(0).record()


def _spec() -> CellSpec:
    return CellSpec(
        build_fn          = _build,
        param_keys        = list(PARAM_KEYS),
        stim_attach_fn    = _attach_stim,
        record_fn         = _attach_record,
        dt                = _DT,
        dt_stim           = _DT_STIM,
        t_max             = _T_MAX,
        v_init            = _V_INIT,
        default_stim_name = "5k50kInterChaoticB",
        stim_dir          = _STIM_DIR,
    )


register("L5PC_jaxley", _spec)
