#!/usr/bin/env python
"""Write the model-ladder design YAMLs (one per rung x stim x training mode).

    rung   : single_comp | ball_and_stick | ball_and_stick_bbp | l5ttpc_nc2 | l5ttpc_nc4
    stim   : 5k50kInterChaoticB (icb) | 5kChaoticRamp (cr)
    mode   : sup  = supervised param-MSE (use_voltage_loss False, tanh-bounded outputs)
             vo   = STRICTLY voltage-only: soft-DTW + small ramped soft-eFEL aux
                    (the CA3 champion recipe, RESULTS_vo.md "Transferable recipe")

File name: ladder_<rung>_<icb|cr>_<sup|vo>.hpar.yaml   (git add -f; *.yaml is ignored).
Everything cell-specific (stim scale, box, defaults) lives in the cell module and the
pack meta, so the YAMLs only carry data path, cell name, stim name, output size.
"""
import os, sys
RUNGS = {   # rung -> (jaxley cell_name_for_sim, cellname token in the pack, n_params, probes)
    "single_comp":        ("soma_only",          "single_comp_synth",        3,  1),
    "ball_and_stick":     ("ball_and_stick",     "ball_and_stick_synth",     4,  2),
    "ball_and_stick_bbp": ("ball_and_stick_bbp", "ball_and_stick_bbp_synth", 13, 1),
    "l5ttpc_nc2":         ("l5ttpc",             "l5ttpc_nc2_synth",         19, 1),
    "l5ttpc_nc4":         ("l5ttpc",             "l5ttpc_nc4_synth",         19, 1),
}
STIMS = {"icb": "5k50kInterChaoticB", "cr": "5kChaoticRamp"}
ROOT = os.environ.get("LADDER_DATA_ROOT", "/global/homes/k/ktub1999/model_ladder_data")   # HOME while pscratch is over quota

COMMON = """data_conf:
    serialize_stims:  True
    append_stim:      False
    parallel_stim:    False
    num_data_workers: 4

max_epochs: {epochs}
batch_size: {bs}

use_manual_features: False
const_local_batch: True
validation_period: [1, 1]
log_freq_per_epoch: 8
tb_show_graph: False
save_checkpoint: True
resume_checkpoint: False
do_ray: False
model_type: CNN

opt_pytorch:
    amp:       False
    apex:      False
    autotune:  False
    zerograd:  False

train_conf:
    warmup_epochs: 0
    optimizer: [adam, {lr}]
    LRsched:   {{ plateau_patience: 10, reduceFactor: 0.3 }}
    clip_grad_norm: {clip}
"""
MODEL = """model:
    myId:    {myid}
    comment: {comment}
    outputSize_override: {P}
    num_cnn_blocks: 2
    conv_block:
        filter: [30, 90, 180]
        kernel: [4,  4,  4]
        pool:   [4,  4,  4]
    instance_norm_slot:  -9
    layer_norm:          False
    batch_norm_cnn_slot: 3
    batch_norm_flat:     True
    fc_block:
       dims:    [512, 512, 512, 256, 128]
       dropFrac: 0.04
"""
SUP = """use_voltage_loss: False
voltage_loss:
    # supervised param-MSE; this block only documents the simulator for evaluate_voltage
    cell_name_for_sim: {cell}
    channel_weight:    1.0
    voltage_weight:    0.0
    mask_channels:     False
    stim_name:         {stim}
    soma_probe_index:  0
    clamp_unit_tanh:   True         # tanh-bounded outputs (project_ca3_supervised_tanh)
    t_max_override:    auto
    solver:            bwd_euler
    fp64:              True
"""
VO = """use_voltage_loss: True
voltage_loss:
    cell_name_for_sim: {cell}
    channel_weight:    0.0
    voltage_weight:    1.0
    mask_channels:     True          # STRICTLY voltage-only: labels never enter the loss
    stim_name:         {stim}
    soma_probe_index:  0
    clamp_unit_tanh:   True
    range_penalty_weight: 0.0
    t_max_override:    auto
    solver:            bwd_euler
    fp64:              True
    # PRIMARY = soft-DTW (timing); AUX = 2 soft-eFEL features (level/amplitude), ramped.
    mse_weight:        0.0
    dtw_weight:        1.0
    dtw_gamma:         0.1
    dtw_n_points:      256
    dtw_band_ms:       8.0
    blur_weight:       0.0
    smooth_sigma:      0.0
    smooth_samples:    1
    lowpass_ms:        0.0
    efel_weight:       0.2
    efel_features:     [voltage_base, AP_amplitude]
    schedule:
        efel_weight:  {{ start: 0.05, end: 0.2, epochs: 20 }}
"""

def write(rung, stag, mode):
    cell, token, P, nprobe = RUNGS[rung]; stim = STIMS[stag]
    name = f"ladder_{rung}_{stag}_{mode}"
    data = f"{ROOT}/{rung}_{stim}/"
    head = (f"# MODEL LADDER ({rung}, {stim}, {'supervised param-MSE' if mode == 'sup' else 'voltage-only soft-DTW + eFEL aux'}).\n"
            f"# Generated by scripts/make_ladder_designs.py -- see docs/model_ladder/README.md.\n"
            f"# Pack: {data}{token}.mlPack1.h5 (stim scaled by the cell module's _STIM_SCALE, recorded in meta).\n"
            f"# {nprobe} data probe(s); voltage loss uses the soma (probe 0).\n\n"
            f"data_path:\n  perlmutter: {data}\n\n")
    if mode == "sup":
        body = COMMON.format(epochs=100, bs=128, lr=0.0003, clip=0) + "\n" + SUP.format(cell=cell, stim=stim)
    else:
        body = COMMON.format(epochs=100, bs=128, lr=0.0001, clip=1.0) + "\n" + VO.format(cell=cell, stim=stim)
    body += "\n" + MODEL.format(myid=name, comment=f"model ladder {rung} {stim} {mode}", P=P)
    open(f"{name}.hpar.yaml", "w").write(head + body)
    return name

if __name__ == "__main__":
    rungs = sys.argv[1].split(",") if len(sys.argv) > 1 else list(RUNGS)
    modes = sys.argv[2].split(",") if len(sys.argv) > 2 else ["sup", "vo"]
    for r in rungs:
        for st in STIMS:
            for m in modes:
                print("wrote", write(r, st, m) + ".hpar.yaml")
